### ISSUE TITLE
Wrong identation

### ISSUE THREAD

**Issue by iget-master** [geochatz/phpstorm-reactjs#1]
When using **rcc** shortcut, the template comes with an wrong/invalid identation as shown in the image:

![ident](https://cloud.githubusercontent.com/assets/9434959/7455141/107324c0-f250-11e4-8d8c-dbd5b545b8da.png)

Note that my entire code is using 4 space identation, but templating is using 1 space identation.

**Comment by reyhansofian** [comment]
You can reformat your code according to your style @iget-master 

![selection_005](https://cloud.githubusercontent.com/assets/5353857/10421410/5d538e82-70d2-11e5-8b4c-86aba69d40c9.jpg)
